# URL (???????? ????????: psql:// ?????? ?? jdbc:postgresql://)
spring.datasource.url=jdbc:postgresql://dpg-d89tqp0jo6nc73e6fgf0-a.oregon-postgres.render.com/task_management_tgyw

# ????? ? ??????
spring.datasource.username=postgres_db
spring.datasource.password=8lxaoNY39ZPT6BmT8WbZ6cdqPX59FQ7o

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true

jwt.secret=your-super-secret-key-must-be-at-least-32-characters-long
jwt.expiration=86400000

spring.security.cors.allowed-origin=http://localhost:5173

server.port=8080
spring.application.name=TaskManagement